### PR TITLE
Consumable class

### PR DESCRIPTION
**Pull request by ldeleau**

### CODE REVIEW

**Review by jalyxis55 — CHANGES_REQUESTED** [review]
From my understanding you should refer to an enumeration by the constant name rather than the number. 

your constructors should be:

super().__init__(...., consumableType=ConsumableType.BREAD)

**Review by patrickv83 — CHANGES_REQUESTED** [review]
Don't forget to write tests for your code, and for some reason automatic linting isn't working so please run pylint manually

**Comment by ldeleau** [comment]
I have absolutely no idea what linting is or how to run this thing. I will try to search but my knowledge of python is zero.

**Comment by patrickv83** [comment]
@ldeleau Linters are static code analyzers that scan code for style, syntax errors, and potential bugs. This is especially useful for interpreted (rather than compiled) languages like python - because interpreted languages lack a compile step, we use a linter (pylint, in our case) to catch the things that a compiler would catch. Running pylint against your source code is very easy, you just run `pylint src/<your source file>`

**Comment by jalyxis55** [comment]
I had never used pylint either, but when it runs there will be messages at the top that tell you which line of the source the message applies to. The messages are pretty self explanatory but if you aren't sure about it, I just Googled "pylint 'message'" and found the meaning really easily. There were somethings that i ignored as well, such as line length, because I didn't change the config file it used to analyze the code.

**Review by jalyxis55 — DISMISSED** [review]

**Comment by ldeleau** [comment]
I have added the test class, and various fixes as recommended by Pylint, and also the changes to the constructor suggested by @jalyxis55 

I added a method to the player class to consume the consumable, and the test method to test it

Please review these changes and merge if appropriate.

**Comment by patrickv83** [comment]
Failing player test

**Pull request merged**
